### ISSUE TITLE
can we deprecate?

### ISSUE THREAD

**Issue by LappleApple** [zalando/system#7]
Last March Igor wrote me back saying that he didn't get a reply about taking this over as a side project, as per his proposal. Doesn't look like things have moved forward with this project since. Do you think there's a last-ditch chance to revive it? Should we keep it on our org page at all?

We might also want to update the README: "Full documentation can be found under the /docs directory of the app. The final 1.0.0 version is expected to be ready by Summer 2013."

**Comment by igoramadas** [comment]
Seems we won't have the resources to work on the System App anytime soon so yes, we can officially deprecate it (I was the sole developer).
